/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProbeAiRouteImport } from './routes/probe.ai'
import { Route as ProbeEditorRouteImport } from './routes/probe.editor'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ExportsDraftsDraftIdRouteImport } from './routes/exports/drafts/$draftId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeAiRoute = ProbeAiRouteImport.update({
  id: '/probe/ai',
  path: '/probe/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeEditorRoute = ProbeEditorRouteImport.update({
  id: '/probe/editor',
  path: '/probe/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsDraftsDraftIdRoute = ExportsDraftsDraftIdRouteImport.update({
  id: '/exports/drafts/$draftId',
  path: '/exports/drafts/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/probe/ai': typeof ProbeAiRoute
  '/probe/editor': typeof ProbeEditorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/exports/drafts/$draftId': typeof ExportsDraftsDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/probe/ai': typeof ProbeAiRoute
  '/probe/editor': typeof ProbeEditorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/exports/drafts/$draftId': typeof ExportsDraftsDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/probe/ai': typeof ProbeAiRoute
  '/probe/editor': typeof ProbeEditorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/exports/drafts/$draftId': typeof ExportsDraftsDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/probe/ai'
    | '/probe/editor'
    | '/api/auth/$'
    | '/exports/drafts/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/probe/ai'
    | '/probe/editor'
    | '/api/auth/$'
    | '/exports/drafts/$draftId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/probe/ai'
    | '/probe/editor'
    | '/api/auth/$'
    | '/exports/drafts/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProbeAiRoute: typeof ProbeAiRoute
  ProbeEditorRoute: typeof ProbeEditorRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ExportsDraftsDraftIdRoute: typeof ExportsDraftsDraftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe/ai': {
      id: '/probe/ai'
      path: '/probe/ai'
      fullPath: '/probe/ai'
      preLoaderRoute: typeof ProbeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe/editor': {
      id: '/probe/editor'
      path: '/probe/editor'
      fullPath: '/probe/editor'
      preLoaderRoute: typeof ProbeEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports/drafts/$draftId': {
      id: '/exports/drafts/$draftId'
      path: '/exports/drafts/$draftId'
      fullPath: '/exports/drafts/$draftId'
      preLoaderRoute: typeof ExportsDraftsDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProbeAiRoute: ProbeAiRoute,
  ProbeEditorRoute: ProbeEditorRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ExportsDraftsDraftIdRoute: ExportsDraftsDraftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
