/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DraftsDraftIdRouteImport } from './routes/drafts.$draftId'
import { Route as IdeasIndexRouteImport } from './routes/ideas.index'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas.$ideaId'
import { Route as ProbeAiRouteImport } from './routes/probe.ai'
import { Route as ProbeEditorRouteImport } from './routes/probe.editor'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ExportsDraftsDraftIdRouteImport } from './routes/exports/drafts/$draftId'
import { Route as ApiDraftsDraftIdComposeRouteImport } from './routes/api/drafts/$draftId.compose'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsDraftIdRoute = DraftsDraftIdRouteImport.update({
  id: '/drafts/$draftId',
  path: '/drafts/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/ideas/$ideaId',
  path: '/ideas/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeAiRoute = ProbeAiRouteImport.update({
  id: '/probe/ai',
  path: '/probe/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeEditorRoute = ProbeEditorRouteImport.update({
  id: '/probe/editor',
  path: '/probe/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsDraftsDraftIdRoute = ExportsDraftsDraftIdRouteImport.update({
  id: '/exports/drafts/$draftId',
  path: '/exports/drafts/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftsDraftIdComposeRoute = ApiDraftsDraftIdComposeRouteImport.update({
  id: '/api/drafts/$draftId/compose',
  path: '/api/drafts/$draftId/compose',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/probe/ai': typeof ProbeAiRoute
  '/probe/editor': typeof ProbeEditorRoute
  '/ideas/': typeof IdeasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/exports/drafts/$draftId': typeof ExportsDraftsDraftIdRoute
  '/api/drafts/$draftId/compose': typeof ApiDraftsDraftIdComposeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/probe/ai': typeof ProbeAiRoute
  '/probe/editor': typeof ProbeEditorRoute
  '/ideas': typeof IdeasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/exports/drafts/$draftId': typeof ExportsDraftsDraftIdRoute
  '/api/drafts/$draftId/compose': typeof ApiDraftsDraftIdComposeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/probe/ai': typeof ProbeAiRoute
  '/probe/editor': typeof ProbeEditorRoute
  '/ideas/': typeof IdeasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/exports/drafts/$draftId': typeof ExportsDraftsDraftIdRoute
  '/api/drafts/$draftId/compose': typeof ApiDraftsDraftIdComposeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/drafts/$draftId'
    | '/ideas/$ideaId'
    | '/probe/ai'
    | '/probe/editor'
    | '/ideas/'
    | '/api/auth/$'
    | '/exports/drafts/$draftId'
    | '/api/drafts/$draftId/compose'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/drafts/$draftId'
    | '/ideas/$ideaId'
    | '/probe/ai'
    | '/probe/editor'
    | '/ideas'
    | '/api/auth/$'
    | '/exports/drafts/$draftId'
    | '/api/drafts/$draftId/compose'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/drafts/$draftId'
    | '/ideas/$ideaId'
    | '/probe/ai'
    | '/probe/editor'
    | '/ideas/'
    | '/api/auth/$'
    | '/exports/drafts/$draftId'
    | '/api/drafts/$draftId/compose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  DraftsDraftIdRoute: typeof DraftsDraftIdRoute
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
  ProbeAiRoute: typeof ProbeAiRoute
  ProbeEditorRoute: typeof ProbeEditorRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ExportsDraftsDraftIdRoute: typeof ExportsDraftsDraftIdRoute
  ApiDraftsDraftIdComposeRoute: typeof ApiDraftsDraftIdComposeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/$draftId': {
      id: '/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/drafts/$draftId'
      preLoaderRoute: typeof DraftsDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe/ai': {
      id: '/probe/ai'
      path: '/probe/ai'
      fullPath: '/probe/ai'
      preLoaderRoute: typeof ProbeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe/editor': {
      id: '/probe/editor'
      path: '/probe/editor'
      fullPath: '/probe/editor'
      preLoaderRoute: typeof ProbeEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports/drafts/$draftId': {
      id: '/exports/drafts/$draftId'
      path: '/exports/drafts/$draftId'
      fullPath: '/exports/drafts/$draftId'
      preLoaderRoute: typeof ExportsDraftsDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts/$draftId/compose': {
      id: '/api/drafts/$draftId/compose'
      path: '/api/drafts/$draftId/compose'
      fullPath: '/api/drafts/$draftId/compose'
      preLoaderRoute: typeof ApiDraftsDraftIdComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  DraftsDraftIdRoute: DraftsDraftIdRoute,
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
  ProbeAiRoute: ProbeAiRoute,
  ProbeEditorRoute: ProbeEditorRoute,
  IdeasIndexRoute: IdeasIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ExportsDraftsDraftIdRoute: ExportsDraftsDraftIdRoute,
  ApiDraftsDraftIdComposeRoute: ApiDraftsDraftIdComposeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
