/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as DraftsDraftIdRouteImport } from './routes/drafts.$draftId'
import { Route as IdeasIndexRouteImport } from './routes/ideas.index'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas.$ideaId'
import { Route as IdeasNewRouteImport } from './routes/ideas.new'
import { Route as ProbeAiRouteImport } from './routes/probe.ai'
import { Route as ProbeEditorRouteImport } from './routes/probe.editor'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaMediaIdRouteImport } from './routes/api/media.$mediaId'
import { Route as ExportsDraftsDraftIdRouteImport } from './routes/exports/drafts/$draftId'
import { Route as ApiDraftsDraftIdComposeRouteImport } from './routes/api/drafts/$draftId.compose'
import { Route as ApiIdeasIdeaIdChatRouteImport } from './routes/api/ideas/$ideaId.chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsDraftIdRoute = DraftsDraftIdRouteImport.update({
  id: '/drafts/$draftId',
  path: '/drafts/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdeasRoute,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => IdeasRoute,
} as any)
const IdeasNewRoute = IdeasNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IdeasRoute,
} as any)
const ProbeAiRoute = ProbeAiRouteImport.update({
  id: '/probe/ai',
  path: '/probe/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeEditorRoute = ProbeEditorRouteImport.update({
  id: '/probe/editor',
  path: '/probe/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaMediaIdRoute = ApiMediaMediaIdRouteImport.update({
  id: '/$mediaId',
  path: '/$mediaId',
  getParentRoute: () => ApiMediaRoute,
} as any)
const ExportsDraftsDraftIdRoute = ExportsDraftsDraftIdRouteImport.update({
  id: '/exports/drafts/$draftId',
  path: '/exports/drafts/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftsDraftIdComposeRoute = ApiDraftsDraftIdComposeRouteImport.update({
  id: '/api/drafts/$draftId/compose',
  path: '/api/drafts/$draftId/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdeasIdeaIdChatRoute = ApiIdeasIdeaIdChatRouteImport.update({
  id: '/api/ideas/$ideaId/chat',
  path: '/api/ideas/$ideaId/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/ideas/new': typeof IdeasNewRoute
  '/probe/ai': typeof ProbeAiRoute
  '/probe/editor': typeof ProbeEditorRoute
  '/ideas/': typeof IdeasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/exports/drafts/$draftId': typeof ExportsDraftsDraftIdRoute
  '/api/drafts/$draftId/compose': typeof ApiDraftsDraftIdComposeRoute
  '/api/ideas/$ideaId/chat': typeof ApiIdeasIdeaIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/ideas/new': typeof IdeasNewRoute
  '/probe/ai': typeof ProbeAiRoute
  '/probe/editor': typeof ProbeEditorRoute
  '/ideas': typeof IdeasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/exports/drafts/$draftId': typeof ExportsDraftsDraftIdRoute
  '/api/drafts/$draftId/compose': typeof ApiDraftsDraftIdComposeRoute
  '/api/ideas/$ideaId/chat': typeof ApiIdeasIdeaIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/ideas/new': typeof IdeasNewRoute
  '/probe/ai': typeof ProbeAiRoute
  '/probe/editor': typeof ProbeEditorRoute
  '/ideas/': typeof IdeasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/exports/drafts/$draftId': typeof ExportsDraftsDraftIdRoute
  '/api/drafts/$draftId/compose': typeof ApiDraftsDraftIdComposeRoute
  '/api/ideas/$ideaId/chat': typeof ApiIdeasIdeaIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas'
    | '/login'
    | '/settings'
    | '/api/media'
    | '/drafts/$draftId'
    | '/ideas/$ideaId'
    | '/ideas/new'
    | '/probe/ai'
    | '/probe/editor'
    | '/ideas/'
    | '/api/auth/$'
    | '/api/media/$mediaId'
    | '/exports/drafts/$draftId'
    | '/api/drafts/$draftId/compose'
    | '/api/ideas/$ideaId/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/api/media'
    | '/drafts/$draftId'
    | '/ideas/$ideaId'
    | '/ideas/new'
    | '/probe/ai'
    | '/probe/editor'
    | '/ideas'
    | '/api/auth/$'
    | '/api/media/$mediaId'
    | '/exports/drafts/$draftId'
    | '/api/drafts/$draftId/compose'
    | '/api/ideas/$ideaId/chat'
  id:
    | '__root__'
    | '/'
    | '/ideas'
    | '/login'
    | '/settings'
    | '/api/media'
    | '/drafts/$draftId'
    | '/ideas/$ideaId'
    | '/ideas/new'
    | '/probe/ai'
    | '/probe/editor'
    | '/ideas/'
    | '/api/auth/$'
    | '/api/media/$mediaId'
    | '/exports/drafts/$draftId'
    | '/api/drafts/$draftId/compose'
    | '/api/ideas/$ideaId/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasRoute: typeof IdeasRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiMediaRoute: typeof ApiMediaRouteWithChildren
  DraftsDraftIdRoute: typeof DraftsDraftIdRoute
  ProbeAiRoute: typeof ProbeAiRoute
  ProbeEditorRoute: typeof ProbeEditorRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ExportsDraftsDraftIdRoute: typeof ExportsDraftsDraftIdRoute
  ApiDraftsDraftIdComposeRoute: typeof ApiDraftsDraftIdComposeRoute
  ApiIdeasIdeaIdChatRoute: typeof ApiIdeasIdeaIdChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/$draftId': {
      id: '/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/drafts/$draftId'
      preLoaderRoute: typeof DraftsDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof IdeasRoute
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof IdeasRoute
    }
    '/ideas/new': {
      id: '/ideas/new'
      path: '/new'
      fullPath: '/ideas/new'
      preLoaderRoute: typeof IdeasNewRouteImport
      parentRoute: typeof IdeasRoute
    }
    '/probe/ai': {
      id: '/probe/ai'
      path: '/probe/ai'
      fullPath: '/probe/ai'
      preLoaderRoute: typeof ProbeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe/editor': {
      id: '/probe/editor'
      path: '/probe/editor'
      fullPath: '/probe/editor'
      preLoaderRoute: typeof ProbeEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$mediaId': {
      id: '/api/media/$mediaId'
      path: '/$mediaId'
      fullPath: '/api/media/$mediaId'
      preLoaderRoute: typeof ApiMediaMediaIdRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/exports/drafts/$draftId': {
      id: '/exports/drafts/$draftId'
      path: '/exports/drafts/$draftId'
      fullPath: '/exports/drafts/$draftId'
      preLoaderRoute: typeof ExportsDraftsDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts/$draftId/compose': {
      id: '/api/drafts/$draftId/compose'
      path: '/api/drafts/$draftId/compose'
      fullPath: '/api/drafts/$draftId/compose'
      preLoaderRoute: typeof ApiDraftsDraftIdComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ideas/$ideaId/chat': {
      id: '/api/ideas/$ideaId/chat'
      path: '/api/ideas/$ideaId/chat'
      fullPath: '/api/ideas/$ideaId/chat'
      preLoaderRoute: typeof ApiIdeasIdeaIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IdeasRouteChildren {
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
  IdeasNewRoute: typeof IdeasNewRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
}

const IdeasRouteChildren: IdeasRouteChildren = {
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
  IdeasNewRoute: IdeasNewRoute,
  IdeasIndexRoute: IdeasIndexRoute,
}

const IdeasRouteWithChildren = IdeasRoute._addFileChildren(IdeasRouteChildren)

interface ApiMediaRouteChildren {
  ApiMediaMediaIdRoute: typeof ApiMediaMediaIdRoute
}

const ApiMediaRouteChildren: ApiMediaRouteChildren = {
  ApiMediaMediaIdRoute: ApiMediaMediaIdRoute,
}

const ApiMediaRouteWithChildren = ApiMediaRoute._addFileChildren(
  ApiMediaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasRoute: IdeasRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiMediaRoute: ApiMediaRouteWithChildren,
  DraftsDraftIdRoute: DraftsDraftIdRoute,
  ProbeAiRoute: ProbeAiRoute,
  ProbeEditorRoute: ProbeEditorRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ExportsDraftsDraftIdRoute: ExportsDraftsDraftIdRoute,
  ApiDraftsDraftIdComposeRoute: ApiDraftsDraftIdComposeRoute,
  ApiIdeasIdeaIdChatRoute: ApiIdeasIdeaIdChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
